version: '3'
services:
  mano:
    container_name: mano
    build: .
    image: mano
    command: bash run_works.sh
    volumes:
      - ./conf/works.yml:/mano/conf/works.yml
      - ./works:/mano/works
